name: Detect Changes

on:
  push:
    branches:
      - master

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          
      - name: Set output
        id: set_output
        run: |
          echo "files=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Display changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt
