name: Detect Changes

on:
  push:
    branches:
      - master

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List changed files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > changed_files.txt
          
      - name: Read changed files
        id: read_files
        run: |
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Display changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.read_files.outputs.files }}"
