name: Detect Changes

on:
  push:
    branches:
      - master

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List changed files
        run: |
          git diff --name-only ${{ github.base_ref }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt  # Выводим содержимое файла для проверки

      - name: Save changed files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: changed_files
          path: changed_files.txt

      - name: Display changed files
        run: cat changed_files.txt
