name: Detect Changes

on:
  push:
    branches:
      - master

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List changed files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt || echo "No files changed"
          
      - name: Set output
        id: set_output
        run: |
          echo "files=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Display changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt
