name: Detect Changes

on:
  push:
    branches:
      - master

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List changed files
        run: |
          if ! git diff --quiet --exit-code ${{ github.base_ref }} ${{ github.sha }}; then
            echo "Git diff command failed or there are no changes."
            exit 1
          else
            echo "Git diff command executed successfully."
          fi
          git diff --name-only ${{ github.base_ref }} ${{ github.sha }} > changed_files.txt
          
      - name: Display changed files
        run: |
          sleep 1
          cat changed_files.txt

      - name: Save changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed_files
          path: changed_files.txt
