name: Upload to FTP Hosting

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./build
          server-dir: htdocs
