name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        host: 	ftpupload.net
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 21
        rm: true
        source: "./*"
        target: "htdocs/"
