name: Deploy to Server

on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIA6ODU6WWC2NOZA25H
          aws_secret_access_key: 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
          aws_bucket: svytogorsk
          source_dir: 'public'

            
       
