name: Deploy to Server

on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shallwefootball/upload-s3-action@v1.3.3
        name: Upload S3
        id: S3
        with:
          aws_key_id: AKIA6ODU6WWCRHZAGW2W
          aws_secret_access_key: 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
          aws_bucket: svytogorsk
          source_dir: 'public'

            
       
