name: Deploy to Server

on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload S3
      - uses: actions/checkout@v4
      - uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          aws_key_id: AKIA6ODU6WWC2NOZA25H
          aws_secret_access_key: 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
          aws_bucket: svytogorsk
          source_dir: 'public'

            
       
