name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 	ftpupload.net
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 21
        protocol: FTP
        local-dir: "https://github.com/vitalik1970/svytogorskOnline/build/static/"
        server-dir: "www.filemanager.ai/new/#/c/185.27.134.11/b12_35910752/eyJ0IjoiZnRwIiwiYyI6eyJ2IjowLCJwIjoiMmttZDNwZm4ifX0/"
